amacneil/dbmate

Dockerfile, main.go
`urfave/cli` now supports returning errors directly from actions
=> Update CLI action signatures

Makefile, README.md
Building with `CGO_ENABLED=0` results in a binary which can run on Alpine linux (with musl libc), but it also disables SQLite support.
Adding an additional target allows people to decide this tradeoff for themselves.
=> Add musl target for Alpine support

mysql.go, mysql_test.go
The postgres `pq` driver already uses a default port if none is passed, but the mysql driver does not. This commit adds a default port 3306 for mysql connections.
=> Add default port for mysql connections

.gitignore, Dockerfile, cmd/dbmate/main.go, docker-compose.yml, pkg/dbmate/db.go, pkg/dbmate/db_test.go, pkg/dbmate/driver.go, pkg/dbmate/mysql.go, pkg/dbmate/mysql_test.go, pkg/dbmate/postgres.go, pkg/dbmate/postgres_test.go, pkg/dbmate/sqlite.go, pkg/dbmate/sqlite_test.go, pkg/dbmate/utils.go, pkg/dbmate/utils_test.go
Implements a `dbmate dump` command to write the database schema to a file.
The intent is for this file to be checked in to the codebase, similar to Rails' `schema.rb` (or `structure.sql`) file. This allows developers to share a single file documenting the database schema, and makes it considerably easier to review PRs which add (or change) migrations.
TODO:
Closes https://github.com/amacneil/dbmate/issues/5
=> Implement schema dumps

pkg/dbmate/driver.go, pkg/dbmate/driver_test.go, pkg/dbmate/mysql.go, pkg/dbmate/postgres.go, pkg/dbmate/sqlite.go, pkg/dbmate/sqlite_test.go
Required to upgrade https://github.com/mattn/go-sqlite3 which does not compile correctly with missing cgo.
=> Add cgo build constraint for sqlite support

README.md, pkg/dbmate/db.go, pkg/dbmate/migrations.go, pkg/dbmate/migrations_test.go
Addresses #46 
This PR adds support for options. The only option implemented here is `transaction` which runs the the migration outside of a transaction when `false`. This is useful for certain statements which cannot run inside of a transaction, such as the `ALTER TYPE` statement used for adding values to enums in Postgres.
I took care to make sure this didn't break any existing functionality, but please point out if I missed something.
I'd love to end-to-end test this, but not every db in the test suite supports PG's enum syntax. I'm sure we could restructure some of the tests such that we end-to-end test this, but I only have so much time I can spend on this. For now, it's unit tested and should cover all the necessary cases.
=> Add support for options; transaction option

README.md, pkg/dbmate/migrations.go, pkg/dbmate/migrations_test.go
This fixes panics that occur under two conditions when parsing a migration file:
* There is no space between `--` and `migrate:[up|down]`
* Neither an up or down migration block was defined
Both the previous implementation (before options were introduced in #68) and existing code would not run migrations under those two circumstances. However, the difference is that previously dbmate silently did nothing and now the code panics. This PR fixes the panics in the following ways:
* Allow 0 or more spaces between `--` and `migrate:[up|down]`
* Explicitly require at least an up block to be defined and fail with a sensical error message when the up block is omitted
To be clear, the fixes in this PR introduce new behavior: 1) allowing something that previously would silently no-op to succeed and …
=> Require presence of up block; optional space after --

pkg/dbmate/migrations.go, pkg/dbmate/migrations_test.go
Addresses #75 
The idea is to fail if there are statements defined outside of the `-- migrate:up` or `-- migrate:down` blocks.
For example, this will succeed:
```sql
-- migrate:up
create table users (id serial);
-- migrate:down
drop table users;
```
This will also succeed:
```sql
-- create users table
-- migrate:up
create table users (id serial);
-- migrate:down
drop table users;
```
But this will fail:
```sql
-- create status_type
create type status_type as enum ('active', 'inactive');
-- migrate:up
create table users (id serial, status status_type);
-- migrate:down
drop table users;
```
=> Fail if statements precede up/down migration blocks

pkg/dbmate/mysql.go, pkg/dbmate/mysql_test.go
This PR aims to fix #57 
When MySQL password included special chars such as exclamation point or @ (at) MySQL backend errored out (invalid password).
https://github.com/amacneil/dbmate/blob/87c22515a9511c680e0391199cc3f53e0fc57eaf/pkg/dbmate/mysql.go#L21-L39
url.userinfo.String() (which gets called inside url.String()) returns %-encoded strings and MySQL interprets it as an actual password.
Now the function percent-decodes it first before returning.
This PR adds a test to cover special chars in MySQL.
=> Fix special chars passwords in MySQL Driver

main.go
Currently, when the .env file cannot be parsed, the dbmate application
bombs with no explanation.  This commit prints out the error.
=> Provide a reasonable error message to users

Dockerfile
Docker builds based on the latest `golang` image are failing due to the change from Debian stretch to buster. 
Pin build to stretch until we are ready to make this transition.
=> Fix docker build for latest golang images

Dockerfile, Makefile, go.mod, pkg/dbmate/mysql_test.go
Adds support for cross-compiling macOS and Windows builds with cgo (using https://github.com/techknowlogick/xgo).
Closes #41
=> Cross-compile macOS and Windows builds

docker-compose.yml, pkg/dbmate/postgres_test.go
Add a default user password to fix CI failures caused by [breaking upstream change](https://github.com/docker-library/postgres/pull/658) in `postgres` docker image.
Example error: https://travis-ci.org/amacneil/dbmate/builds/631760202
=> Add default docker postgres password

README.md, main.go, pkg/dbmate/db.go
Per suggestions from @MarkMurphy and @maximelebastard: extending the `dbmate status` command with the ability to set an exit code or quiet output, for use in scripts.
Flag names were copied from `git diff` command.
Also thanks to @fernandocarletti @hmleal @matguig for previous suggestions and PRs relating to this feature.
=> Add --exit-code and --quiet flags to status command

README.md, pkg/dbmate/mysql_test.go, pkg/dbmate/postgres.go, pkg/dbmate/postgres_test.go
Simplifies connecting to postgres via sockets (https://github.com/amacneil/dbmate/issues/107), and standardize the `socket` parameter across both mysql and postgresql.
=> Add postgres support for socket parameter

Dockerfile, Makefile, README.md
Prior to this commit, we released two linux binaries:
* `dbmate-linux-amd64` (built with cgo, dynamically linked)
* `dbmate-linux-musl-amd64` (built without cgo, statically linked, no sqlite support)
The statically linked binary is desirable for alpine linux users (or anyone else using musl libc or minimal docker images). The original reason for having two separate binaries was that the easiest method to create a static binary for go is to set `CGO_ENABLED=0`, but unfortunately this also prevented us from building sqlite (which requires cgo).
With this commit, all linux and windows binaries are explicitly statically linked while leaving cgo enabled. Hat tip to https://www.arp242.net/static-go.html which explained the necessary flags to enable this.
As an added bonus, the `dbmate` docker …
=> Build statically linked binaries

Dockerfile
Instead of a nice super-minimal production docker image, create one based on alpine with sql clients installed (`mariadb-client`, `postgresql-client`, and `sqlite`).
* Increases docker image size from 10 MB to 56 MB 👎 
* Allows people to run `dbmate dump` command with our docker image (fixes #114) 👍 
* I'm not sure what compatibility is like between `mysqldump` from `mariadb-client` versus `mysql-client`, but starting here since mariadb is included with alpine, and the version I built using mysql and ubuntu weighed in at 165 MB. 🤔
=> Add sql clients to docker image

README.md
Closes https://github.com/amacneil/dbmate/issues/159
=> Document migration order

README.md, pkg/dbmate/driver.go, pkg/dbmate/postgres.go, pkg/dbmate/postgres_test.go, pkg/dbmate/utils.go
Instead of hardcoding `schema_migrations` table to the `public` schema, add support for specifying a schema via the `search_path` URL parameter.
**Backwards compatibility note**: If anyone was using the previously undocumented `search_path` behavior (affecting migrations themselves, but always storing the `schema_migrations` table in `public`), you will need to either prepend `public` to your `search_path`, or migrate your `schema_migrations` table to your primary schema:
```sql
ALTER TABLE public.schema_migrations SET SCHEMA myschema;
```
cc @RabidFire
Closes #110
=> postgres: Support custom schema for schema_migrations table

README.md, pkg/dbmate/clickhouse.go, pkg/dbmate/clickhouse_test.go, pkg/dbmate/db.go, pkg/dbmate/driver.go, pkg/dbmate/mysql.go, pkg/dbmate/mysql_test.go, pkg/dbmate/postgres.go, pkg/dbmate/postgres_test.go, pkg/dbmate/sqlite.go, pkg/dbmate/sqlite_test.go
In https://github.com/amacneil/dbmate/pull/167 we added support for specifying a postgres `search_path`, which is used to store the `schema_migrations` table. However, if the schema does not already exist it will cause an error.
In this PR we automatically create the first schema in the `search_path` if it does not exist.
=> postgres: Automatically create search_path schema when needed

pkg/dbmate/mysql.go
This pull request force the `schema_migrations` table to be created with `latin1` character set, to fix the behavior of `dbmate` in MariaDB 10.1 and older (or MySQL 5.5 and older) when the system charset has more than 1 byte per character (e.g. utf8mb4) - see #85
=> Create the schema_migrations table using latin1 charset in MySQL

main.go, pkg/dbmate/clickhouse.go, pkg/dbmate/clickhouse_test.go, pkg/dbmate/db.go, pkg/dbmate/db_test.go, pkg/dbmate/driver.go, pkg/dbmate/driver_test.go, pkg/dbmate/mysql.go, pkg/dbmate/mysql_test.go, pkg/dbmate/postgres.go, pkg/dbmate/postgres_test.go, pkg/dbmate/sqlite.go, pkg/dbmate/sqlite_test.go, pkg/dbmate/utils.go, pkg/dbmate/utils_test.go
Supported via `--migrations-table` CLI flag or `DBMATE_MIGRATIONS_TABLE` environment variable.
Specified table name is quoted when necessary.
For PostgreSQL specifically, it's also possible to specify a custom schema (for example: `--migrations-table=foo.migrations`).
Closes https://github.com/amacneil/dbmate/issues/168
=> Ability to specify custom migrations table name

pkg/dbmate/db.go, pkg/dbmate/driver.go, pkg/driver/clickhouse/clickhouse.go, pkg/driver/mysql/mysql.go, pkg/driver/postgres/postgres.go, pkg/driver/sqlite/sqlite.go
This makes it possible to redirect the logs somewhere else, useful if you embed dbmate into your application.
=> Write log lines to DB.Log output

pkg/dbmate/db.go, pkg/dbmate/db_test.go
make the "invalid url" error message give more information for somebody that hasn't ready documentation and just runs the application
**Input**
```sh
dbmate up
```
**Output**
```
Error: invalid url, have you set your --url flag or DATABASE_HOST environment variable?
```
=> make the "invalid url" error message give more information

pkg/driver/mysql/mysql.go, pkg/driver/mysql/mysql_test.go
This addresses #199 which I just opened. As the [documentation][pathunescape] says:
> PathUnescape is identical to QueryUnescape except that it does not unescape '+' to ' ' (space).
I think that makes sense, since `+` in passwords gets converted to a space otherwise, and this isn't correct.
[pathunescape]: https://golang.org/pkg/net/url/#PathUnescape
=> mysql: Use url.PathUnescape instead of url.QueryEscape so that '+' in passwords works

.github/workflows/ci.yml, .github/workflows/publish-docker.sh, .vscode/settings.json, docker-compose.yml
Docker Hub no longer supports free container builds for open source.
Publish to both Docker Hub and GitHub Container Registry.
=> Publish Docker image

pkg/driver/postgres/postgres.go, pkg/driver/postgres/postgres_test.go
Closes #229
When there's no host given in a postgres connection url, use the unix
domain default socket. Previously, the default was a localhost TCP
connection. This default behavior is more in line with standard postgres
clients out there, like psql.
=> Postgres defaults to unix socket with no host

Makefile, docker-compose.yml
The official `mysql:5.7` docker image does not work on arm64 (e.g. Apple M1), nor does `mysql:8.0`.
`mysql/mysql-server:8.0` appears to be maintained by Oracle and is equally "official", so switching to that for the time being.
=> Update to MySQL 8.0 image for testing

pkg/dbmate/db.go, pkg/dbmate/db_test.go, pkg/dbmate/driver.go, pkg/driver/clickhouse/clickhouse.go, pkg/driver/mysql/mysql.go, pkg/driver/postgres/postgres.go, pkg/driver/sqlite/sqlite.go
So we have this use case where our developers have read-only access to our databases, and want to be able to run `dbmate status` before running a migration as part of our CI/CD pipeline.
Surprisingly, `dbmate status` has the potential side-effect of creating the migrations table if it's not there, which fails for a read only user.
This change makes the Status command read only by checking if the table exists, and returning all migrations as pending if it doesn't (and works as expected otherwise).
=> Make Status read only

pkg/dbutil/dbutil.go, pkg/driver/sqlite/sqlite.go, pkg/driver/sqlite/sqlite_test.go
When the DSN is in the form `sqlite:/absolute/path` or `sqlite://absolute/path` or `sqlite:///absolute/path`, url.Parse
will consider the file path as:
- `absolute` as the hostname
- `path` (and the rest until `?`) as the URL path.
Instead, when the DSN is in the form "sqlite:", the (relative) file path is stored in the "Opaque" field.
See: https://pkg.go.dev/net/url#URL
While Opaque is not escaped, the URL Path is. So, in absolute paths the full file path is being escaped as if it was an URL path.
This commit works around this behavior in `ConnectionString()` (`sqlite.go`) so that the return string is always a correct (url-unescaped) file path.
Fixes #264 .
=> Fix whitespace issues in SQLite absolute paths in DATABASE_URL

pkg/driver/sqlite/sqlite_test.go
Follow up from https://github.com/amacneil/dbmate/pull/266:
> Do we have any tests for the `sqlite://foo/bar.sqlite` (two leading slashes) behavior you described? I can’t see any.
_Originally posted by @amacneil in https://github.com/amacneil/dbmate/issues/266#issuecomment-1025199749_
=> sqlite: Add test for two slashes in URL

Makefile
Was broken in previous release due to refactor of our CI. 
As noticed in https://github.com/ScoopInstaller/Main/pull/3204#issuecomment-1016224196
=> Append .exe to Windows builds

drivers.go, drivers_cgo.go, main.go
This moves the database driver imports into separate files:
* one for sqlite with cgo build constraint and
* one for all the others.
This makes it possible to compile dbmate without sqlite again.
Fixes #284
=> Move sqlite driver import behind build constraint

.github/workflows/ci.yml
Currently I use dbmate on my CI about some projects and my CI is running on some raspberry.
In this merge request, I provide the configuration for the github actions to build an arm32 (armv7) version of dbmate.
=> Add arm32 cross compilation on github action

pkg/driver/mysql/mysql.go, pkg/driver/mysql/mysql_test.go
=> Trim AUTO_INCREMENT values from MySQL schema dumps

Dockerfile
This makes it so that the `caching_sha2_password `  plugin is included so connections to Mysql > 8.0 can succeed.
fixes: #307
=> Include `mariadb-connector-c` (#307)

docker-compose.yml, pkg/driver/clickhouse/clickhouse.go, pkg/driver/clickhouse/clickhouse_test.go
- Upgraded `clickhouse-server` image to v22.8 the latest LTS version
- Updated the tests since the error messages are different in v22
- Fixed `CREATE DATABASE IF NOT EXISTS` based on the official document https://github.com/amacneil/dbmate/issues/379
=> Fix create db and upgrade clickhouse-server to v22.8

main.go, pkg/dbmate/db.go, pkg/dbmate/db_test.go, pkg/dbmate/driver.go, pkg/driver/clickhouse/clickhouse_test.go, pkg/driver/mysql/mysql_test.go, pkg/driver/postgres/postgres_test.go, pkg/driver/sqlite/sqlite_test.go
- Always wait for database (if `db.WaitBefore` is true) during driver creation
- Simplify some code by creating driver multiple times instead of passing `drv` around
=> Always wait when creating driver

pkg/driver/clickhouse/clickhouse.go, pkg/driver/clickhouse/clickhouse_test.go
Checking for the migration tables existence in Clickhouse shouldn't pass a parameter.
This could be acheived one of two ways:
- Use Sprintf to add the table name to the query (this is what is used elsewhere within the Clickhouse driver)
- Check the `information_schema` using `currentDatabase()`.
Opted for the first as that is what is used elsewhere.
Fixes #301
=> Clickhouse: Fix CheckMigrationTableExists

pkg/dbmate/db.go, pkg/dbmate/db_test.go, pkg/dbmate/migration.go, pkg/dbmate/migration_test.go
Support passing `fs.FS` to support embedded filesystems. Defaults to the directory filesystem.
Also cleaned up `Migration` object and parsing, and simplified `FindMigrations()` to always return the application status of each migration.
Closes https://github.com/amacneil/dbmate/issues/193
Closes https://github.com/amacneil/dbmate/pull/346
=> Support embedded filesystem migrations

pkg/driver/sqlite/sqlite.go, pkg/driver/sqlite/sqlite_test.go
Pass the `--nosys` flag through to the SQLite `.schema` command. This will stop the `sqlite` command from writing out system tables `sqlite_*`.
This flag is documented:
```
sqlite> .help .schema
.schema ?PATTERN?        Show the CREATE statements matching PATTERN
Options:
--indent             Try to pretty-print the schema
--nosys              Omit objects whose names start with "sqlite_"
```
I wasn't sure if this would constitute a breaking change so I didn't hide it behind a flag as the issue was marked as `Bug`, but I'm happy to add this if it is correct to.
This was also quite hard to test as the test suite passed with or without the `--nosys` flag. I'm presuming this is a change in SQLite but I couldn't find a reference to it. I added a test any way just to make sure it doesn't creap …
=> SQLite: Do not dump system tables

pkg/driver/mysql/mysql.go, pkg/driver/postgres/postgres.go, pkg/driver/sqlite/sqlite.go
- Use default charset for mysql
- Change version column from `varchar(256)` to `varchar(128)` to avoid issues with utf8mb4 on mysql. Made this change on all drivers for consistency.
Refs:
- https://github.com/amacneil/dbmate/discussions/390
- https://github.com/amacneil/dbmate/issues/85
=> Shorter version column, use default charset for mysql

README.md, pkg/dbmate/migration.go, pkg/dbmate/migration_test.go
- Always require down directive
- Require up migration before down migration
Closes https://github.com/amacneil/dbmate/issues/108
=> Stricter migration parsing

pkg/dbmate/db.go, pkg/dbmate/db_test.go, pkg/dbmate/migration.go
Closes https://github.com/amacneil/dbmate/issues/403
=> Fix absolute migration directory support

pkg/dbmate/db.go, pkg/dbmate/db_test.go
There's a small issue with a pointer that only allows one rollback to work: #404 
This PR fixes the issue and adds a second rollback in the test case to prove that it works now.
Fixes https://github.com/amacneil/dbmate/issues/404
=> Fix subsequent rollbacks

.github/workflows/ci.yml
Takes a long time to build cross-platform docker images, and I'm not convinced anyone is using docker on this architecture. We still provide an arm32 binary.
=> Remove arm32 docker image

typescript/package.json, typescript/packages/dbmate/package.json, typescript/packages/dbmate/src/resolveBinary.ts, typescript/packages/dbmate/tsconfig.json, typescript/tsconfig.json
Exporting an ESM package is difficult for CommonJS consumers, and the benefits of using ESM are minimal since we only target Node.js.
Therefore, we export a CommonJS package instead (which will still work fine for all ESM Node.js consumers).
=> Publish as CommonJS module

main.go, pkg/dbmate/db.go, pkg/dbmate/db_test.go
For reference, see:
https://github.com/amacneil/dbmate/discussions/424
=> Support multiple --migrations-dir directories

pkg/driver/postgres/postgres.go, pkg/driver/postgres/postgres_test.go
As stated in #445, the MigrationsTableExists function does not properly query when the schema contains special characters, since it is then querying for the quoted value.
This PR makes it use unquoted values instead, and adds tests for this behaviour (the tests will fail on the current main branch).
=> Postgres: Add support for schemas containing special characters

.github/workflows/ci.yml, Makefile
With "Docker version 20.10.24, build 297e128" the command `make docker-all` throws the following message:
```
WARNING: Some service image(s) must be built from source by running:
docker compose build dbmate
1 error occurred:
* Error response from daemon: pull access denied for dbmate_release, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
make: *** [Makefile:61: docker-all] Error 18
```
With this fix docker does not pull the images that we build afterwards anyway.
=> Fix docker test command

README.md
Passwords with special characters must be URL encoded (percent encoded) when using the DATABASE_URL variable. Otherwise an error might pop up from net/url package when parsing. So it is probably better to mention that in the documentation.
=> Update README.md about percent encoding DATABASE_URL

.github/workflows/ci.yml
Compile ARM binary for ARMv6, so it works on my first gen Raspberry Pi. Previously we only supported ARMv7.
=> Add ARMv6 support

README.md, main.go, pkg/dbmate/db.go, pkg/dbmate/db_test.go
This adds the `--strict-order` flag which ignores all out of order pending migrations. With the flag set `dbmate up` and `dbmate migrate` only apply pending migrations which succeed the latest applied migration - in other words, only pending migrations with a higher version number than the latest applied migration will be used. `dbmate --strict-order status` also only lists in order pending migrations. Rollbacks work as usual.
Refs: #159
=> Add --strict flag

pkg/driver/mysql/mysql.go
This PR addresses #444
Dbmate currently fails to function against MySQL instances enabled with the [ANSI_QUOTES](https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_ansi_quotes) sql_mode.
My initial investigation report [can be found here](https://github.com/amacneil/dbmate/issues/444#issuecomment-1719787799).
The ANSI_QUOTES mode does not allow double-quote characters to be used for expressing string literals. Therefore ANSI_QUOTES-enabled MySQL rejects the following query produced by Dbmate's MySQL driver:
```
SHOW TABLES LIKE "schema_migrations"
```
From: https://github.com/amacneil/dbmate/blob/6245b8c/pkg/driver/mysql/mysql.go#L236
MySQL driver's [quotedMigrationsTableName()](https://github.com/amacneil/dbmate/blob/6245b8c/pkg/driver/mysql/mysql.go#L316) complies with …
=> MySQL: Add ANSI_QUOTES support to MigrationsTableExists()

pkg/dbmate/db.go, pkg/dbmate/db_test.go, pkg/dbmate/driver.go, pkg/driver/clickhouse/clickhouse.go, pkg/driver/mysql/mysql.go, pkg/driver/postgres/postgres.go, pkg/driver/sqlite/sqlite.go
Postgres's database driver returns the character position where a syntax error occurs, so dbmate can use that information to calculate the line and column within the query that the position refers to.                         
This PR supersedes the work from PR #204, simplifying the implementation a bit by minimizing the amount of code change required, plus adding additional tests, including SQL queries with UTF-8 characters present.
=> Add line/column/position details to Postgres migration/rollback query error messages

Makefile
Sometimes, it's nice to be able to run just a subset of the test suite.  This change to the `Makefile` enables one to do this:
```sh
$ make test FLAGS='-run "^TestCasePrefix"'
```
Limited usefulness, but without the change to the `Makefile`, this isn't possible, so here's a PR.
=> Make appending to FLAGS possible when invoking make.

.github/dependabot.yml, .gitignore, .vscode/settings.json, Dockerfile
Pin Go and Alpine container image versions, and enable Dependabot for docker images.
This means we will get notified of new Go releases which typically include security fixes.
Also unrelated:
- Commit eslint setting that keeps updating itself
- Revert adding `.vscode` to `.gitignore` from https://github.com/amacneil/dbmate/pull/432
=> Enable dependabot for docker images

pkg/dbmate/db.go
=> fix: embedded fs on windows

Makefile
This PR aims for solving this [issue](https://github.com/amacneil/dbmate/issues/539).
After launching `make docker-all` in local environment, the execution of tests, as explained in README, is satisfactorily. Sharing snippet below:
```sh
WARN[0000] /workspaces/dbmate/docker-compose.yml: `version` is obsolete 
[+] Creating 7/0
✔ Container dbmate-clickhouse-1             Running                                                                                             0.0s 
✔ Container dbmate-bigquery-1               Running                                                                                             0.0s 
✔ Container dbmate-mysql-1                  Running                                                                                             0.0s 
✔ Container …
```
=> Enable timeout flag in `make fix`.

.github/workflows/ci.yml, .gitignore, Makefile, docker-compose.yml, pkg/dbmate/db_test.go, pkg/driver/bigquery/bigquery_test.go, pkg/driver/clickhouse/clickhouse_cluster_test.go, pkg/driver/clickhouse/clickhouse_testutils_test.go, pkg/driver/mysql/mysql_test.go, pkg/driver/postgres/postgres_test.go, pkg/driver/sqlite/sqlite_test.go
- Run unit tests on all platforms to discover/prevent issues like https://github.com/amacneil/dbmate/issues/536
- Change dbmate package unit tests to use sqlite instead of postgres (i.e. no external dependency, although sqlite binary is currently still required due to `dbmate dump` tests)
- Integration tests can be run by passing the appropriate env vars such as `POSTGRES_TEST_URL`. If URLs are not provided they will be skipped.
- In CI we only run integration tests in the linux docker job.
=> CI: Run tests on all platforms

pkg/dbmate/db_test.go, pkg/dbtest/dbtest.go, pkg/dbutil/dbutil.go, pkg/dbutil/dbutil_test.go, pkg/driver/bigquery/bigquery_test.go, pkg/driver/clickhouse/clickhouse.go, pkg/driver/clickhouse/clickhouse_cluster_test.go, pkg/driver/clickhouse/clickhouse_test.go, pkg/driver/clickhouse/clickhouse_testutils_test.go, pkg/driver/clickhouse/cluster_parameters_test.go, pkg/driver/mysql/mysql_test.go, pkg/driver/postgres/postgres.go, pkg/driver/postgres/postgres_test.go, pkg/driver/sqlite/sqlite_test.go
Reduce duplication in tests and consistent messages for skipped integration tests.
=> Clean up test helper functions

README.md, pkg/dbmate/db.go, pkg/dbmate/db_test.go
Example output
```
Applying: 20230110131043_change-updated_at-fields.sql
Applied: 20230110131043_change-updated_at-fields.sql in 45.098471ms
```
=> prints the migrate/rollback execution time

README.md, docker-compose.yml, pkg/driver/postgres/postgres.go, pkg/driver/postgres/postgres_test.go
Adds support for the [GCP Spanner Postgres Interface](https://cloud.google.com/spanner/docs/postgresql-interface), which only requires a slight modification to the postgres driver.
This will not work with a GoogleSQL-flavored Spanner database; support for that will require a dedicated driver.
The new functionality is accessed with a custom `spanner-postgres://` scheme. This is rather un-standard and something I just made up, so the exact scheme is open for debate. We shouldn't use just `spanner://`, since that may cause confusion down the line when a driver for Spanner with the GoogleSQL dialect is added.
Related discussion: https://github.com/amacneil/dbmate/discussions/369
=> Spanner Postgres interface support

Makefile, pkg/driver/sqlite/sqlite_test.go
This statically compiles in the FTS5 module, allowing dbmate to handle migrations that use the full-text search features of SQLite.
Issue #237 raised the question of handling migrations that included FTS5 tables. It was later converted to a discussion (#357).
It is possible to enable the feature in the statically-compiled SQLite that ships with dbmate via a feature flag. Adding the `sqlite_fts5` flag to the `Makefile` embeds this feature statically.
An additional test was added with a `CREATE VIRTUAL TABLE` statement that leverages the FTS5 module. This test fails when dbmate is compiled _without_ the feature flag. After adding the flag, this test passes.
`make test` and `make docker-all` pass.
Confirmed that it works in practice locally on Ubuntu 22.04.  
For information about the …
=> Enable FTS5 in SQLite migrations

go.mod, go.sum
Description:
This PR updates golang.org/x/crypto to the latest version (v0.31.0) to mitigate the security vulnerability identified as [CVE-2024-45337](https://nvd.nist.gov/vuln/detail/CVE-2024-45337).
Summary of Changes:
Updated go.mod to require golang.org/x/crypto@v0.31.0.
Ran go mod tidy to clean up dependencies.
Why This Change Is Important:
The previously used version of golang.org/x/crypto was affected by CVE-2024-45337. Upgrading to v0.31.0 resolves this issue and ensures the library remains secure and up-to-date.
Impact:
No breaking changes are expected as v0.31.0 is backward-compatible with prior versions.
Improves the security posture of the project by addressing a critical vulnerability.
References:
CVE-2024-45337: https://nvd.nist.gov/vuln/detail/CVE-2024-45337
Golang …
=> Upgrade golang.org/x/crypto to v0.31.0

pkg/driver/postgres/postgres.go
These are sometimes needed in the pq library, but are not supported when calling pg_dump.
=> Remove binary_parameters from pg_dump database url

.golangci.yml, main_test.go, pkg/dbmate/db_test.go
[`usetesting`](https://golangci-lint.run/usage/linters/#usetesting) tells that we can replace `os.Setenv` with `t.Setenv` and `os.MkdirTemp` with `t.TempDir`. As a result, this slightly simplifies tests.
```sh
$ golangci-lint run
pkg/dbmate/db_test.go:112:14: os.MkdirTemp() could be replaced by t.TempDir() in TestDumpSchema (usetesting)
dir, err := os.MkdirTemp("", "dbmate")
^
pkg/dbmate/db_test.go:146:14: os.MkdirTemp() could be replaced by t.TempDir() in TestAutoDumpSchema (usetesting)
dir, err := os.MkdirTemp("", "dbmate")
^
pkg/dbmate/db_test.go:190:14: os.MkdirTemp() could be replaced by t.TempDir() in TestLoadSchema (usetesting)
dir, err := os.MkdirTemp("", "dbmate")
^
pkg/dbmate/db_test.go:559:15: os.MkdirTemp() could be replaced by t.TempDir() in TestFindMigrationsAbsolute …
```
=> Enable usetesting linter and simplify tests

Dockerfile, go.mod
Bumping to patch for a CVE in the Go std lib: https://nvd.nist.gov/vuln/detail/CVE-2025-22871
Note: Overrides (or requires) https://github.com/amacneil/dbmate/pull/647
=> [CVE-2025-22871] Bump Module's Go Toolchain to 1.24.3

docker-compose.yml
A change to the [Google Cloud Spanner PGAdapter and Spanner Emulator][1] in v0.48.4 is breaking our `dbmate` test.
[1]: https://github.com/GoogleCloudPlatform/pgadapter?tab=readme-ov-file#emulator
Our tests did not pin to a particular version, resulting in our tests starting to fail with no change to dbmate.
```shell
spanner-emulator:
image: gcr.io/cloud-spanner-pg-adapter/pgadapter-emulator:v0.48.4
=== RUN   TestSpannerPostgresCreateMigrationsTable
=== RUN   TestSpannerPostgresCreateMigrationsTable/default_schema
postgres_test.go:83:
Error Trace:    /src/pkg/driver/postgres/postgres_test.go:83
/src/pkg/driver/postgres/postgres_test.go:451
Error:          Received unexpected error:
pq: NOT_FOUND: io.grpc.StatusRuntimeException: NOT_FOUND: Input file …
```
=> Pin Spanner pgadapter-emulator to v0.48.3
